export const icons = {
    add: require("@/assets/icons/Add.png"),
    add_active: require("@/assets/icons/Add_full.png"),
    back: require("@/assets/icons/Back.png"),
    bad: require("@/assets/icons/Bad.png"),
    close: require("@/assets/icons/Close.png"),
    good: require("@/assets/icons/Good.png"),
    home: require("@/assets/icons/Home.png"),
    home_active: require("@/assets/icons/Home_full.png"),
    logo: require("@/assets/icons/Logo.png"),
    medical: require("@/assets/icons/Medical_icon.png"),
    next: require("@/assets/icons/Next.png"),
    scan: require("@/assets/icons/Scan.png"),
    search: require("@/assets/icons/Search.png"),
    search_active: require("@/assets/icons/Search_full.png"),
    user: require("@/assets/icons/User.png"),
    user_active: require("@/assets/icons/User_full.png"),
    login: require("@/assets/icons/Lock.png"),
    logout: require("@/assets/icons/Logout.png"),
    camera: require("@/assets/icons/Camera.png"),
    error: require("@/assets/icons/Error.png"),
    fiber: require("@/assets/icons/Fiber.png"),
    changeAvatar: require("@/assets/icons/Photo_Gallery.png"),
    changePassword: require("@/assets/icons/Key.png"),
    box: require("@/assets/icons/Box.png"),
};
export default icons;
